{% set name = "restructuredtext_lint" %}
{% set version = "1.4.0" %}
{% set sha256 = "1b235c0c922341ab6c530390892eb9e92f90b9b75046063e047cacfb0f050c45" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0
  entry_points:
    - rst-lint = restructuredtext_lint.cli:main
    - restructuredtext-lint = restructuredtext_lint.cli:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools

  run:
    - python >=3.6
    - docutils >=0.11,<1.0

test:
  imports:
    - restructuredtext_lint
  commands:
    - rst-lint -h
    - restructuredtext-lint -h

about:
  home: https://github.com/twolfson/restructuredtext-lint
  license: Unlicense
  license_file: UNLICENSE
  license_family: Public-Domain
  summary: Lint reStructuredText files
  dev_url: https://github.com/twolfson/restructuredtext-lint

extra:
  recipe-maintainers:
    - dopplershift
